# Changes here will be overwritten by Copier
_commit: 1.2.6
_src_path: gh:pawamoy/copier-pdm
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2022'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: false
project_description: A spell checker plugin for MkDocs.
project_name: MkDocs SpellCheck
python_package_command_line_name: ''
python_package_distribution_name: mkdocs-spellcheck
python_package_import_name: mkdocs_spellcheck
repository_name: mkdocs-spellcheck
repository_namespace: pawamoy
repository_provider: github.com

